sudo: required

language: ruby

rvm:
  - 2.2.3

git:
  depth: 25

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - docker build -t rmarchei/gisgraphy-db .
  - docker run -d -p 127.0.0.1:5432:5432 --name gisgraphy-db rmarchei/gisgraphy-db && sleep 10
  - docker ps -a
  - docker exec -it gisgraphy-db id
  - docker exec -it gisgraphy-db pwd

script:
  - psql -U postgres -h localhost -p 5432 -wqtl | cut -d \| -f 1 | grep -w gisgraphy
