sudo: required

language: ruby

rvm:
  - 2.2.3

git:
  depth: 25

services:
  - docker

before_install:
  - docker build -t rmarchei/gisgraphy-db .
  - docker run -d -p 127.0.0.1:5432:5432 --name gisgraphy-db rmarchei/gisgraphy-db
  - docker ps -a
  - docker exec -it gisgraphy-db id
  - docker exec -it gisgraphy-db pwd
